Mieubrisse/dynamic networks
kurtosis-tech/ZZ-DEPRECATED_kurtosis pull request #107
Opened 2020-06-23 09:29 UTC by mieubrisse

2020-06-23 11:22 UTC, galenmarchetti requested changes

2020-06-23 11:22 UTC, galenmarchetti commented on CHANGELOG.md
> +* Force the user to provide a static configuration ID, so they can reference it later in their tests
can you add more details here? configuration ID for what? network, services, each test, etc

2020-06-23 11:22 UTC, galenmarchetti commented on commons/docker/docker_manager.go
>  	volumeConfig := volume.VolumeCreateBody{
oh baby

2020-06-23 11:22 UTC, galenmarchetti commented on commons/docker/docker_manager.go
>  	bindMounts: mapping of (host file) -> (mountpoint on container) that will be mounted at container startup
can we add a comment here that explains when we should be using bind mounts vs when we should be using volumes? right now it seems like duplicate functionality, although I imagine there's a reason we're retaining both

2020-06-23 11:22 UTC, galenmarchetti commented on commons/networks/service_network.go
> +	IpAddr string
YESS

2020-06-23 11:22 UTC, galenmarchetti commented on commons/networks/service_network.go
> +// Adds a service to the graph, with the specified dependencies (with the map used only as a set - the values are ignored)
IMO "dependencies" are not clear...can we add more information in this comment about what kinds of things constitute dependencies?

I know in the ava specific context its "serivices ids of bootstrappers", but in the generalized context it's not clear to me what I should be expect to be able to do with the dependencies

2020-06-23 11:22 UTC, galenmarchetti commented on commons/testsuite/test_network_loader.go
> +	Returns: A map of serviceId -> availability checkers that indicate that the network is started if all checkers return
whoa nice

2020-06-23 11:22 UTC, galenmarchetti commented on commons/networks/public_ip_tracker.go
> +func NewFreeIpAddrTracker(subnetMask string, alreadyTakenIps []string) (ipAddrTracker *FreeIpAddrTracker, err error) {
why are we adding the "alreadyTakenIps" to this constructor? what would be the use of this parameter?

2020-06-24 09:59 UTC, mieubrisse commented on CHANGELOG.md
> +* Force the user to provide a static configuration ID, so they can reference it later in their tests
Done

2020-06-24 09:59 UTC, mieubrisse commented on commons/docker/docker_manager.go
>  	volumeConfig := volume.VolumeCreateBody{
:D

2020-06-24 10:02 UTC, mieubrisse commented on commons/docker/docker_manager.go
>  	bindMounts: mapping of (host file) -> (mountpoint on container) that will be mounted at container startup
Yep! Added:
```
	bindMounts: Mapping of (host file) -> (mountpoint on container) that will be mounted at container startup (used when
		sharing data between the host filesystem - in our case, the test initializer - and a Docker container)
	volumeMounts: Mapping of (volume name) -> (mountpoint on container) that will be mounted at container startup (used
		when sharing data between containers). This is distinct from a bind mount because the host filesystem can't easily
		read from a Docker volume - you need to be inside a Docker container to do so.
```
LMK if that makes sense; biggest distinction is that as the host, you actually can't easily write to a Docker volume because Docker _itself_ lives inside a VM. So in the initializer when you create a volume, you get back a filepath that's relative to the Docker VM and doing File.Write will give you filepath not found.

2020-06-24 10:06 UTC, mieubrisse commented on commons/networks/service_network.go
> +// Adds a service to the graph, with the specified dependencies (with the map used only as a set - the values are ignored)
new docs for the function; lmk if this resolves:
```
Adds a service to the graph that depends on the services with the given IDs
Args:
	configurationId: The ID of the service configuration to use for creating the service
	serviceId: The ID to give the node in the network
	dependencies: A "set" of service IDs that the node-to-create depends on - i.e., whose information the node-to-create
		needs to start up. If the node-to-create doesn't depend on any other services, the dependencies map should be
		empty (not nil).
Return:
	An AvailabilityChecker for checking when the service is actually available
```

2020-06-24 10:07 UTC, mieubrisse commented on commons/networks/public_ip_tracker.go
> +func NewFreeIpAddrTracker(subnetMask string, alreadyTakenIps []string) (ipAddrTracker *FreeIpAddrTracker, err error) {
Yep so, this is used in the `testController`. The reason for it is that the TestController (who now does network construction) needs to know which IPs are already in use in the subnet that he lives inside, so he doesn't dole them out new services. As of right now, the two IPs that will be in use will be the Gateway IP and the test controller IP itself. This is also why GATEWAY_IP and TEST_CONTROLLER_IP are now arguments to the TestContorller

2020-06-24 11:08 UTC, galenmarchetti approved these changes

2020-06-24 11:09 UTC, merged