Writes gob of service data to file
kurtosis-tech/ZZ-DEPRECATED_kurtosis pull request #67
Opened 2020-05-30 18:02 UTC by mieubrisse

We're almost ready to Do The Thing!!!!!

2020-05-31 09:22 UTC, galenmarchetti requested changes

2020-05-31 09:22 UTC, galenmarchetti commented on initializer/test_suite_runner.go
> +	println(fmt.Sprintf("%v", rawServiceNetwork))
can we replace this with a log statement?

2020-05-31 09:22 UTC, galenmarchetti commented on initializer/test_suite_runner.go
>  	// Apparently, per https://www.joeshaw.org/dont-defer-close-on-writable-files/ , file.Close() can return errors too,
so why defer the close? can we just call tmpfile.Close() and throw an error if closing fails?

2020-05-31 13:11 UTC, mieubrisse commented on initializer/test_suite_runner.go
>  	// Apparently, per https://www.joeshaw.org/dont-defer-close-on-writable-files/ , file.Close() can return errors too,
It's to make sure that a panic anywhere will still close the file (if a panic happens, a regular Close call won't get called). AFAICT, an error from Close is something you can't do anything about (I'm not even sure what the remediation steps would be - stopping the program seems wrong)

2020-05-31 13:11 UTC, mieubrisse commented on initializer/test_suite_runner.go
> +	println(fmt.Sprintf("%v", rawServiceNetwork))
Fixed in latest PR

2020-06-02 09:46 UTC, galenmarchetti approved these changes

2020-06-02 09:46 UTC, merged