Mieubrisse/migrate test from controller
kurtosis-tech/ZZ-DEPRECATED_kurtosis pull request #69
Opened 2020-05-31 03:55 UTC by mieubrisse

It works!!!!

2020-05-31 09:31 UTC, galenmarchetti requested changes

2020-05-31 09:31 UTC, galenmarchetti commented on ava_commons/testsuite/ava_test_suite.go
> +	result["singleNodeGetValidatorsTest"] = testsuite.TestConfig{
I think we need to make sure master is always running a testnet, not a single node. otherwise we have loss of functionality on a deliverable item (running network). can we either make the number of nodes configurable (CLI flag for choosing single node vs ten node) or just make sure to switch the default back a testnet before we merge? this also guarantees that our CI is running checks on the multiple-node testnet setup, rather than just the single one.

i know in principle its the same thing but we're beholden to kurtosis running an entire testnet and i wanna make sure we're consistently keeping that state on master

2020-05-31 13:05 UTC, mieubrisse commented on ava_commons/testsuite/ava_test_suite.go
> +	result["singleNodeGetValidatorsTest"] = testsuite.TestConfig{
Yep so the right way to do it I think is #71 ; agreed that we don't want to keep making codechanges to swap between these

2020-06-02 09:48 UTC, galenmarchetti commented on ava_commons/testsuite/ava_test_suite.go
> +	result["singleNodeGetValidatorsTest"] = testsuite.TestConfig{
okay, i'll merge this to keep code velocity going. but we really need to get #71 in now, otherwise we're losing core functionality

2020-06-02 09:49 UTC, galenmarchetti approved these changes

2020-06-02 09:49 UTC, merged